services:
  tapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tapp-backend
    env_file:
      - .env
    environment:
      DB_HOST: tapp-db
    ports:
      - "8080:8080"
    depends_on:
      - tapp-db

  tapp-dashboard:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: tapp-dashboard
    ports:
      - "3001:80"
    depends_on:
      - tapp-backend

  tapp-nfc:
    build:
      context: .
      dockerfile: Dockerfile.nfc
    container_name: tapp-nfc
    profiles:
      - nfc
    environment:
      NFC_API_URL: http://tapp-backend:8080/api/nfc
      NFC_POLL_INTERVAL: 1
    depends_on:
      - tapp-backend
    restart: unless-stopped

  tapp-db:
    image: postgres:15
    container_name: tapp-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - tapp-db-data:/var/lib/postgresql/data
  
volumes:
  tapp-db-data:
